export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";
export const INCREMENTDASHBOARD = "INCREMENTDASHBOARD";
export const DECREMENTDASHBOARD = "DECREMENTDASHBOARD";
export const RESETDASHBOARD = "RESETDASHBOARD";